# Deploy Sphinx-built documentation (docs/_build/html) to GitHub Pages
name: Deploy docs to Pages

on:
  push:
    # Change this to your default branch if different
    branches: ["lib-ela_doc"]
    paths:
      - 'docs/_build/html/**'
      - '.github/workflows/static.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # If you commit pre-built HTML (docs/_build/html already in repo),
      # you do NOT need a build step. If you prefer to build here instead,
      # remove the commit of built files and uncomment the build block below.

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'
      #
      # - name: Install dependencies & build docs
      #   run: |
      #     pip install -r docs/requirements.txt
      #     make -C docs html

      - name: Upload artifact (built docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
